import Header from '@/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<>
				<body className={inter.className}>
					<AuthProvider>
						<Header />
						<main className="h-[562px] bg-white text-black w-full">
							{children}
						</main>
						<Footer />
					</AuthProvider>
				</body>
			</>
		</html>
	);
}
